// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.services.sync.engine.bookmarks.buffer", true);
user_pref("app.normandy.user_id", "7eb0eb4d-da3b-4ba1-b4b9-27c11cc4f65e");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1576911632);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1576911752);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1576921952);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1576911392);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1576911272);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1576911512);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1576911182);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1576911872);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 20824);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1576911121);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3d966b08-76db-4097-8408-e582791e76ac}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1576920338194");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1576922113194");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1576921956916");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1576925556916");
user_pref("browser.search.region", "PH");
user_pref("browser.slowStartup.averageTime", 14107);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191205184924");
user_pref("browser.startup.homepage_override.mstone", "71.0");
user_pref("browser.startup.lastColdStartupCheck", 1576911130);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "71.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "8389ff6ef80a468baa33c862248ee818");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 20 Dec 2019 22:42:36 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1576911633);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "71.0");
user_pref("extensions.lastPlatformVersion", "71.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"05ae44df-17f8-4b4d-a365-eb2b24a59788\",\"screenshots@mozilla.org\":\"004d6589-15c9-42ee-97d6-8060e80e5fad\",\"webcompat-reporter@mozilla.org\":\"9e0b6a27-9453-43af-adb1-2abd0aa3b33c\",\"webcompat@mozilla.org\":\"89ab7228-0616-491b-a6db-7a4b265b258f\",\"default-theme@mozilla.org\":\"67c1ed39-3956-4c93-a78a-3f1f8e93fd16\",\"google@search.mozilla.org\":\"000a2dc7-c06d-43f5-8fd1-4b5c7a68062b\",\"amazondotcom@search.mozilla.org\":\"5c779ea2-ffcb-4bb4-9780-3965339d54f0\",\"bing@search.mozilla.org\":\"265a7fb7-7a61-4e41-831f-2e9ffb6594ab\",\"ddg@search.mozilla.org\":\"f3c1392f-3ff2-4aa7-8397-42e6e9568931\",\"ebay@search.mozilla.org\":\"b6ac381d-fc3e-4211-8fb3-de53ba8d6663\",\"twitter@search.mozilla.org\":\"a0a8a8dc-6382-4848-b487-07c9a48d76dc\",\"wikipedia@search.mozilla.org\":\"e496bc86-9f73-4744-b914-db79119ab84f\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("idle.lastDailyNotification", 1576911682);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1576911392);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191205184924");
user_pref("media.gmp-manager.lastCheck", 1576911390);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1576911683);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "6dbd5e02-aedd-4174-9c31-b6b1bac80df0");
user_pref("security.sandbox.plugin.tempDirSuffix", "e12f52f5-68b4-4894-9d42-06b3233aea14");
user_pref("services.blocklist.pinning.checked", 1576911814);
user_pref("services.settings.clock_skew_seconds", -302);
user_pref("services.settings.last_etag", "\"1576886481064\"");
user_pref("services.settings.last_update_seconds", 1576911814);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1576911814);
user_pref("services.settings.main.cfr-fxa.last_check", 1576911814);
user_pref("services.settings.main.cfr.last_check", 1576911814);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1576911814);
user_pref("services.settings.main.hijack-blocklists.last_check", 1576911814);
user_pref("services.settings.main.language-dictionaries.last_check", 1576911814);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1576911814);
user_pref("services.settings.main.public-suffix-list.last_check", 1576911814);
user_pref("services.settings.main.sites-classification.last_check", 1576911814);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1576911814);
user_pref("services.settings.main.whats-new-panel.last_check", 1576911814);
user_pref("services.settings.security.onecrl.checked", 1576911814);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1576911683);
user_pref("toolkit.startup.last_success", 1576911115);
user_pref("toolkit.telemetry.cachedClientID", "12c1197c-2820-42dc-b54c-04706789db47");
user_pref("toolkit.telemetry.previousBuildID", "20191205184924");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("trailhead.firstrun.interruptsExperiment", "modal_control");
